Widok profilu uzytkownika
bazaragh/bazaragh pull request #58
Opened 2023-05-22 20:03 UTC by HulekJakub

2023-05-23 09:04 UTC, paulinagacek commented
@HulekJakub po co nowa karta na profil użytkownika? Powielane są dane z zakładki Dane Osobowe

2023-05-23 11:32 UTC, paulinagacek commented
@HulekJakub @sokoloowski  czy mogę używać takiej konstrukcji do przekierowywania? ```<button class="custom-button" onclick=window.location.href="{{url_for('bp_main.user_get_offers', user_id=user.id)}}">pokaż oferty sprzedającego</button>```

2023-05-23 15:12 UTC, HulekJakub commented
> @HulekJakub @sokoloowski czy mogę używać takiej konstrukcji do przekierowywania? `<button class="custom-button" onclick=window.location.href="{{url_for('bp_main.user_get_offers', user_id=user.id)}}">pokaż oferty sprzedającego</button>`

A <a> jak w base.jinja nie wystarczy?
<a class="dropdown-item-custom main-navbar-item"
    href="{{url_for('bp_user.profile_get')}}">Moje
    dane</a>

2023-05-23 15:41 UTC, paulinagacek commented
@HulekJakub można, ale wtedy to nie będzie button tylko anchor

2023-05-23 15:47 UTC, paulinagacek commented
@sokoloowski jeśli nie ma zastrzeżeń proszę o merge

2023-05-23 21:54 UTC, sokoloowski commented
Lepiej `<a>` ostylować jak przycisk

2023-05-23 22:03 UTC, sokoloowski requested changes
Drobne poprawki, żeby tego nie zgubić w przyszłości

2023-05-23 22:03 UTC, sokoloowski commented on app/templates/offer/offer.jinja
> +                <button class="custom-button">pokaż profilsprzedającego</button>
```diff
- <button class="custom-button">pokaż profilsprzedającego</button>
+ <button class="custom-button">pokaż profil sprzedającego</button>
```

2023-05-23 22:03 UTC, sokoloowski commented on app/templates/user_view.jinja
> +    <button class="custom-button">napisz do sprzedającego</button>
Możemy zrobić od razu link do `/messages/<seller_id>`? (oczywiście z użyciem `url_for`)

2023-05-24 11:22 UTC, paulinagacek commented on app/templates/user_view.jinja
> +    <button class="custom-button">napisz do sprzedającego</button>
zrobione

2023-05-24 11:23 UTC, paulinagacek approved these changes
Jak dla mnie można mergować

2023-05-24 11:59 UTC, HulekJakub commented
Próbowałaś ostylować <a> tak żeby był jak button?
> Jak dla mnie można mergować

2023-05-24 12:20 UTC, sokoloowski approved these changes

2023-05-24 12:20 UTC, sokoloowski commented on app/templates/offer/offer.jinja
> +        {% if not current_user.is_authenticated or current_user.id != author.id%}
Zostawił bym przycisk dla niezalogowanych

2023-05-24 12:27 UTC, paulinagacek commented
@HulekJakub sprawdź czy jest git pls

2023-05-24 16:46 UTC, paulinagacek commented on app/templates/offer/offer.jinja
> +        {% if not current_user.is_authenticated or current_user.id != author.id%}
To jest zostawiony dla niezalogowanych lub dla tych co nie są autorami

2023-05-24 17:20 UTC, HulekJakub reviewed
LGTM

2023-05-24 17:20 UTC, merged